python src/SingleModel.py \
    --model_name "OneLayerMLQP" \
    --data_path "data" \
    --activation "relu" \
    --hidden_size 64 \
    --hidden_size2 32 \
    --learning_rate 1e-4 \
    --epochs 500 \
    --do_train \
    --do_test \
    --visualize_db
