python src/MinMaxModel.py \
    --base_model TwoLayerMLQP \
    --data_split_strategy "PK" \
    --hidden_size 64 \
    --hidden_size2 32 \
    --epochs 500 \
    --learning_rate 1e-4 \
    --activation "sigmoid" \
    --do_train \
    --do_test \
    --multiprocessing \
    --visualize_data_subsets \
    --visualize_MinMax_db \
    --visualize_submodel_db
